// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Götz Kohlberg. All rights reserved.
// Dual licensed: AGPL-3.0 + SIDJUA Commercial License. See LICENSE.

/**
 * SIDJUA — Step 9: COST_CENTERS
 *
 * Generates / merges {workDir}/.system/cost-centers.yaml and syncs the
 * cost_budgets table in the main SQLite database.
 *
 * Merge semantics (idempotent):
 *   - Active divisions present in the existing file: preserve user-set limits
 *   - Active divisions NOT in the existing file: add with null limits
 *   - Divisions no longer active: removed from the YAML (DB rows preserved)
 *   - Global section: preserved if it already exists, else defaulted
 *
 * The YAML is always rewritten (overwrite:true) but user-set limits survive
 * because they are loaded from the existing file before merging.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse, stringify } from "yaml";
import type { ParsedConfig } from "../types/config.js";
import type { CostCentersConfig, DivisionBudget } from "../types/apply.js";
import { ApplyError, type StepResult } from "../types/apply.js";
import type { Database } from "../utils/db.js";
import { logger } from "../utils/logger.js";
import { createLogger } from "../core/logger.js";

const _logger = createLogger("cost-centers");


const DEFAULT_GLOBAL_BUDGET: CostCentersConfig["global"] = {
  monthly_limit_usd: null,
  daily_limit_usd: null,
  alert_threshold_percent: 80,
};

const DEFAULT_DIVISION_BUDGET: DivisionBudget = {
  monthly_limit_usd: null,
  daily_limit_usd: null,
};


/**
 * Load and parse the existing cost-centers.yaml.
 * Returns null if the file does not exist or cannot be parsed.
 */
function loadExistingCostCenters(filePath: string): CostCentersConfig | null {
  if (!existsSync(filePath)) return null;
  try {
    const raw = parse(readFileSync(filePath, "utf-8")) as unknown;
    if (typeof raw !== "object" || raw === null) return null;
    return raw as CostCentersConfig;
  } catch (e: unknown) {
    _logger.debug("cost-centers", "Cost centers config not found or malformed — using defaults", { metadata: { error: e instanceof Error ? e.message : String(e) } });
    return null;
  }
}

/**
 * Merge the existing cost centers config with the current active divisions.
 * Preserves user-set limits, adds new divisions, removes inactive ones.
 */
export function mergeCostCenters(
  existing: CostCentersConfig | null,
  activeDivisionCodes: string[],
): CostCentersConfig {
  const global = existing?.global ?? { ...DEFAULT_GLOBAL_BUDGET };
  const existingDivisions = existing?.divisions ?? {};
  const merged: Record<string, DivisionBudget> = {};

  for (const code of activeDivisionCodes) {
    merged[code] = existingDivisions[code] ?? { ...DEFAULT_DIVISION_BUDGET };
  }

  return {
    schema_version: "1.0",
    generated_at: new Date().toISOString(),
    global,
    divisions: merged,
  };
}

/**
 * Sync the cost_budgets table rows with the values in the cost centers config.
 * Updates limits for active divisions to reflect any user-set values.
 */
function syncCostBudgetsToDb(db: Database, config: CostCentersConfig): void {
  const upsert = db.prepare<[string, number | null, number | null, number], void>(`
    INSERT INTO cost_budgets (division_code, monthly_limit_usd, daily_limit_usd, alert_threshold_percent)
    VALUES (?, ?, ?, ?)
    ON CONFLICT(division_code) DO UPDATE SET
      monthly_limit_usd       = excluded.monthly_limit_usd,
      daily_limit_usd         = excluded.daily_limit_usd,
      alert_threshold_percent = excluded.alert_threshold_percent
  `);

  db.transaction(() => {
    for (const [code, budget] of Object.entries(config.divisions)) {
      const threshold = budget.alert_threshold_percent ?? config.global.alert_threshold_percent;
      upsert.run(code, budget.monthly_limit_usd ?? null, budget.daily_limit_usd ?? null, threshold);
    }
  })();
}


export function applyCostCenters(
  config: ParsedConfig,
  workDir: string,
  db: Database,
): StepResult {
  const start = Date.now();

  try {
    const outPath = join(workDir, ".system", "cost-centers.yaml");
    const existing = loadExistingCostCenters(outPath);

    const activeCodes = config.activeDivisions.map((d) => d.code);
    const merged = mergeCostCenters(existing, activeCodes);

    const added = activeCodes.filter((c) => !existing?.divisions[c]).length;
    const preserved = activeCodes.length - added;

    const yaml =
      `# AUTO-GENERATED by sidjua apply — user limits preserved on re-apply\n` +
      stringify(merged, { indent: 2 });

    writeFileSync(outPath, yaml, "utf-8");

    // Sync DB cost_budgets table with the merged values
    syncCostBudgetsToDb(db, merged);

    logger.info(
      "COST_CENTERS",
      `Cost centers: ${activeCodes.length} budgets configured (${added} new, ${preserved} preserved)`,
    );

    return {
      step: "COST_CENTERS",
      success: true,
      duration_ms: Date.now() - start,
      summary: `${activeCodes.length} budgets configured`,
      details: {
        outPath,
        divisionsTotal: activeCodes.length,
        added,
        preserved,
      },
    };
  } catch (err) {
    throw new ApplyError(
      "GENERATION_ERROR",
      "COST_CENTERS",
      `Cost centers step failed: ${err instanceof Error ? err.message : String(err)}`,
      err,
    );
  }
}
