// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Götz Kohlberg. All rights reserved.
// Dual licensed: AGPL-3.0 + SIDJUA Commercial License. See LICENSE.

/**
 * SIDJUA — Step 5: RBAC
 *
 * Generates {workDir}/.system/rbac.yaml from the validated ParsedConfig.
 * This file is always overwritten on every apply — it is never user-editable.
 *
 * Generation logic (from spec):
 *   - Four fixed roles: system_admin, division_head, division_agent, cross_division_reader
 *   - For each unique head.agent in active divisions → assign division_head role
 *   - Tier-based cross-division read access:
 *       T1 → cross_division_reader for ALL active divisions ("*")
 *       T2 → cross_division_reader for T1-headed divisions
 *       T3 → no cross-division access
 *
 * Agent tier is inferred from the agent_id suffix: *-t1 | *-t2 | *-t3.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { stringify } from "yaml";
import type { ParsedConfig } from "../types/config.js";
import type { RBACConfig, AgentAssignment, RoleDefinition, RoleAssignment } from "../types/apply.js";
import { ApplyError, type StepResult } from "../types/apply.js";
import { logger } from "../utils/logger.js";


const DEFAULT_ROLES: RoleDefinition[] = [
  {
    role: "system_admin",
    permissions: ["*"],
    description: "Full system access (human only)",
  },
  {
    role: "division_head",
    scope: "own_division",
    permissions: [
      "read_all",
      "write_all",
      "approve_tasks",
      "manage_agents",
      "view_audit",
      "view_costs",
      "read_secrets",
      "write_secrets",
      "read_secrets_global",
    ],
  },
  {
    role: "division_agent",
    scope: "own_division",
    permissions: [
      "read_workspace",
      "write_workspace",
      "read_knowledge",
      "read_inbox",
      "write_outbox",
      "create_audit_entry",
      "read_secrets",
      "read_secrets_global",
    ],
  },
  {
    role: "cross_division_reader",
    scope: "specified_divisions",
    permissions: ["read_outbox"],
  },
];


/**
 * Infer agent tier from ID suffix convention: *-t1 | *-t2 | *-t3.
 * Returns null for IDs that don't follow this convention.
 */
export function getAgentTier(agentId: string): 1 | 2 | 3 | null {
  const match = /-(t[123])$/i.exec(agentId);
  if (!match) return null;
  const tier = match[1]?.toLowerCase();
  if (tier === "t1") return 1;
  if (tier === "t2") return 2;
  if (tier === "t3") return 3;
  return null;
}


export function generateRBAC(config: ParsedConfig): RBACConfig {
  // Collect: agent → [divisions it heads]
  const agentDivisions = new Map<string, string[]>();
  for (const div of config.activeDivisions) {
    if (!div.head.agent) continue;
    const existing = agentDivisions.get(div.head.agent) ?? [];
    existing.push(div.code);
    agentDivisions.set(div.head.agent, existing);
  }

  // Find T1-headed division codes (T2 agents need read access to these)
  const t1HeadedDivisions = config.activeDivisions
    .filter((d) => d.head.agent && getAgentTier(d.head.agent) === 1)
    .map((d) => d.code);

  const assignments: AgentAssignment[] = [];

  for (const [agent, divisions] of agentDivisions) {
    const tier = getAgentTier(agent);
    const roles: RoleAssignment[] = [];

    // Division head roles
    for (const divCode of divisions) {
      roles.push({ role: "division_head", division: divCode });
    }

    // Cross-division reader based on tier
    if (tier === 1) {
      // T1: read all active divisions
      roles.push({ role: "cross_division_reader", divisions: ["*"] });
    } else if (tier === 2 && t1HeadedDivisions.length > 0) {
      // T2: read T1-headed divisions (strategic oversight)
      roles.push({ role: "cross_division_reader", divisions: [...t1HeadedDivisions] });
    }
    // T3 and unknown tiers: no cross-division reader

    assignments.push({ agent, roles });
  }

  return {
    schema_version: "1.0",
    generated_at: new Date().toISOString(),
    roles: DEFAULT_ROLES,
    assignments,
  };
}


export function applyRBAC(config: ParsedConfig, workDir: string): StepResult {
  const start = Date.now();

  try {
    const rbac = generateRBAC(config);
    const outPath = join(workDir, ".system", "rbac.yaml");

    const yaml =
      "# AUTO-GENERATED by sidjua apply — DO NOT EDIT MANUALLY\n" +
      stringify(rbac, { indent: 2 });

    writeFileSync(outPath, yaml, "utf-8");

    const agentCount = rbac.assignments.length;
    const roleCount = rbac.assignments.reduce((n, a) => n + a.roles.length, 0);

    logger.info("RBAC", `Generated rbac.yaml: ${agentCount} agents, ${roleCount} role assignments`);

    return {
      step: "RBAC",
      success: true,
      duration_ms: Date.now() - start,
      summary: `${agentCount} agents → ${roleCount} role assignments`,
      details: { agentCount, roleCount, outPath },
    };
  } catch (err) {
    throw new ApplyError(
      "GENERATION_ERROR",
      "RBAC",
      `RBAC step failed: ${err instanceof Error ? err.message : String(err)}`,
      err,
    );
  }
}
