// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Götz Kohlberg. All rights reserved.
// Dual licensed: AGPL-3.0 + SIDJUA Commercial License. See LICENSE.

/**
 * SIDJUA — Step 7: SKILLS
 *
 * Generates {workDir}/{division.code}/.meta/skills.yaml for each active division.
 * Uses division-specific skill templates from spec §7, falling back to _default.
 *
 * CRITICAL: Files are written with overwrite:false — existing user-customised
 * skills.yaml files are NEVER overwritten. Only new (missing) files are created.
 */

import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { stringify } from "yaml";
import type { ParsedConfig } from "../types/config.js";
import { ApplyError, type StepResult } from "../types/apply.js";
import { logger } from "../utils/logger.js";


const DIVISION_SKILL_TEMPLATES: Record<string, string[]> = {
  engineering: ["read_file", "write_file", "execute_code", "git_operations", "deploy"],
  sales: ["read_file", "write_file", "send_email_draft", "crm_access"],
  "customer-service": ["read_file", "write_file", "ticket_management", "knowledge_search"],
  "ai-governance": ["read_file", "write_file", "search_knowledge", "audit_query", "policy_review"],
  executive: ["read_file", "write_file", "search_knowledge", "agent.delegate", "agent.escalate"],
  legal: ["read_file", "write_file", "search_knowledge", "contract.draft"],
  finance: ["read_file", "write_file", "search_knowledge", "data.export"],
  product: ["read_file", "write_file", "search_knowledge", "git_operations"],
  intelligence: ["read_file", "write_file", "web.fetch", "search_knowledge", "data.export"],
  _default: ["read_file", "write_file", "search_knowledge"],
};

/** Skills that require explicit approval before execution */
const HIGH_RISK_SKILLS = new Set([
  "deploy",
  "send_email_draft",
  "data.export",
  "contract.draft",
  "contract.sign",
  "purchase.initiate",
]);


interface SkillEntry {
  name: string;
  scope: string | string[];
  requires_approval: boolean;
}

interface SkillsFile {
  division: string;
  generated_at: string;
  skills: SkillEntry[];
}

export function generateSkillsForDivision(code: string): SkillsFile {
  const template = DIVISION_SKILL_TEMPLATES[code] ?? DIVISION_SKILL_TEMPLATES["_default"] ?? [];
  const skills: SkillEntry[] = template.map((name) => ({
    name,
    scope: "own_division",
    requires_approval: HIGH_RISK_SKILLS.has(name),
  }));

  return {
    division: code,
    generated_at: new Date().toISOString(),
    skills,
  };
}


export function applySkills(config: ParsedConfig, workDir: string): StepResult {
  const start = Date.now();

  try {
    let newFiles = 0;
    let preserved = 0;

    for (const div of config.activeDivisions) {
      const outPath = join(workDir, div.code, ".meta", "skills.yaml");

      if (existsSync(outPath)) {
        preserved++;
        logger.debug("SKILLS", `Preserved existing skills.yaml for "${div.code}"`);
        continue;
      }

      // Ensure .meta dir exists (filesystem step should have created it, but be safe)
      const metaDir = dirname(outPath);
      if (!existsSync(metaDir)) {
        mkdirSync(metaDir, { recursive: true });
      }

      const skillsData = generateSkillsForDivision(div.code);
      const yaml =
        `# AUTO-GENERATED by sidjua apply — customise as needed.\n` +
        `# Re-running apply will NOT overwrite this file.\n` +
        stringify(skillsData, { indent: 2 });

      writeFileSync(outPath, yaml, "utf-8");
      newFiles++;
      logger.debug("SKILLS", `Created skills.yaml for "${div.code}"`);
    }

    logger.info("SKILLS", `Skills: ${newFiles} created, ${preserved} preserved`);

    return {
      step: "SKILLS",
      success: true,
      duration_ms: Date.now() - start,
      summary: `${newFiles} created, ${preserved} preserved`,
      details: { newFiles, preserved },
    };
  } catch (err) {
    throw new ApplyError(
      "GENERATION_ERROR",
      "SKILLS",
      `Skills step failed: ${err instanceof Error ? err.message : String(err)}`,
      err,
    );
  }
}
