// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Götz Kohlberg. All rights reserved.
// Dual licensed: AGPL-3.0 + SIDJUA Commercial License. See LICENSE.

/**
 * SIDJUA — Step 8: AUDIT
 *
 * Initialises per-division audit views in the SQLite DB and provisions the
 * governance/audit/ directory structure.
 *
 * Operations:
 *   1. CREATE VIEW IF NOT EXISTS audit_{code} for each active division
 *      (view filters audit_trail WHERE division_code = '{div.code}')
 *   2. Ensure {workDir}/governance/audit/reports/ directory exists
 *   3. Generate default governance/audit/audit-config.yaml if not present
 *      (overwrite:false — user customisations are NEVER overwritten)
 *
 * Division codes are validated to [a-z0-9-] by Step 1, making them safe
 * for SQL view name interpolation after replacing hyphens with underscores.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { stringify } from "yaml";
import type { ParsedConfig } from "../types/config.js";
import type { AuditConfig } from "../types/apply.js";
import { ApplyError, type StepResult } from "../types/apply.js";
import type { Database } from "../utils/db.js";
import { viewExists } from "../utils/db.js";
import { logger } from "../utils/logger.js";


const DEFAULT_AUDIT_CONFIG: AuditConfig = {
  schema_version: "1.0",
  log_level: "standard",
  events: {
    task_start: true,
    task_complete: true,
    decision: true,
    escalation: true,      // Always true — cannot disable
    governance_check: true, // Always true — cannot disable
    error: true,            // Always true — cannot disable
    approval_request: true, // Always true — cannot disable
    blocked: true,          // Always true — cannot disable
  },
  retention: {
    days: 365,
    export_before_delete: true,
  },
  export: {
    formats: ["json", "csv"],
    include_metadata: true,
  },
};


/**
 * Convert a division code (e.g. "customer-service") to a valid SQLite view
 * name (e.g. "audit_customer_service"). Hyphens → underscores.
 * Division codes are validated [a-z0-9-] so no other substitution is needed.
 */
function viewNameForDivision(code: string): string {
  return `audit_${code.replace(/-/g, "_")}`;
}


export function applyAudit(
  config: ParsedConfig,
  workDir: string,
  db: Database,
): StepResult {
  const start = Date.now();

  try {
    // 1. Create per-division audit views
    let viewsCreated = 0;

    for (const div of config.activeDivisions) {
      const viewName = viewNameForDivision(div.code);

      if (!viewExists(db, viewName)) {
        // Division codes are validated [a-z0-9-] — safe for SQL interpolation.
        // Using string interpolation because CREATE VIEW does not support parameters.
        db.exec(
          `CREATE VIEW IF NOT EXISTS ${viewName} AS ` +
            `SELECT * FROM audit_trail WHERE division_code = '${div.code}'`,
        );
        viewsCreated++;
        logger.debug("AUDIT", `Created audit view "${viewName}" for division "${div.code}"`);
      }
    }

    // 2. Ensure governance/audit/reports/ directory exists
    const reportsDir = join(workDir, "governance", "audit", "reports");
    if (!existsSync(reportsDir)) {
      mkdirSync(reportsDir, { recursive: true });
    }

    // 3. Generate default audit-config.yaml (overwrite:false)
    const auditConfigPath = join(workDir, "governance", "audit", "audit-config.yaml");
    let configCreated = false;

    if (!existsSync(auditConfigPath)) {
      const yaml =
        `# AUTO-GENERATED by sidjua apply — customise as needed.\n` +
        `# Re-running apply will NOT overwrite this file.\n` +
        stringify(DEFAULT_AUDIT_CONFIG, { indent: 2 });

      writeFileSync(auditConfigPath, yaml, "utf-8");
      configCreated = true;
      logger.debug("AUDIT", `Created default audit-config.yaml`);
    }

    const totalViews = config.activeDivisions.length;
    logger.info(
      "AUDIT",
      `Audit: ${viewsCreated} views created, ${totalViews - viewsCreated} existing, export dir verified`,
    );

    return {
      step: "AUDIT",
      success: true,
      duration_ms: Date.now() - start,
      summary: `${totalViews} views, retention: ${DEFAULT_AUDIT_CONFIG.retention.days}d`,
      details: {
        viewsCreated,
        viewsTotal: totalViews,
        exportDirVerified: true,
        auditConfigCreated: configCreated,
        auditConfigPath,
      },
    };
  } catch (err) {
    throw new ApplyError(
      "DATABASE_ERROR",
      "AUDIT",
      `Audit step failed: ${err instanceof Error ? err.message : String(err)}`,
      err,
    );
  }
}
