// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Götz Kohlberg. All rights reserved.
// Dual licensed: AGPL-3.0 + SIDJUA Commercial License. See LICENSE.

/**
 * SIDJUA — Step 6: ROUTING
 *
 * Generates {workDir}/.system/routing-table.yaml from the validated ParsedConfig.
 * Always overwritten on apply — not user-editable.
 *
 * Route per active division:
 *   primary  → division.head.agent (may be null)
 *   fallback → determined by head agent tier:
 *                T3 → first available T2 agent → first available T1 agent → null
 *                T2 → first available T1 agent → null
 *                T1 → null (human escalation)
 *                no head → first available T1 agent → null
 *
 * Default route: highest-tier (lowest tier number) agent with action "classify_and_route"
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { stringify } from "yaml";
import type { ParsedConfig } from "../types/config.js";
import type { RoutingTable, Route } from "../types/apply.js";
import { ApplyError, type StepResult } from "../types/apply.js";
import { getAgentTier } from "./rbac.js";
import { logger } from "../utils/logger.js";


export function generateRoutingTable(config: ParsedConfig): RoutingTable {
  const routes: Route[] = [];

  for (const div of config.activeDivisions) {
    routes.push({
      division: div.code,
      primary: div.head.agent ?? null,
      fallback: determineFallback(div.head.agent, config),
    });
  }

  const defaultAgent = findHighestTierAgent(config) ?? "guide";

  return {
    schema_version: "1.0",
    generated_at: new Date().toISOString(),
    routes,
    default_route: {
      agent: defaultAgent,
      action: "classify_and_route",
    },
  };
}

/**
 * Determine fallback agent for a division based on the primary agent's tier.
 *   T3 primary → try T2, then T1
 *   T2 primary → try T1
 *   T1 primary → null (escalate to human)
 *   null primary → try T1
 */
function determineFallback(primaryAgent: string | null, config: ParsedConfig): string | null {
  if (primaryAgent === null) {
    return findAgentByTier(1, config);
  }
  const tier = getAgentTier(primaryAgent);
  if (tier === 3) {
    return findAgentByTier(2, config) ?? findAgentByTier(1, config);
  }
  if (tier === 2) {
    return findAgentByTier(1, config);
  }
  // T1 or unknown tier → no fallback
  return null;
}

/**
 * Find any active division head with the given tier (lowest division index wins).
 */
export function findAgentByTier(
  tier: 1 | 2 | 3,
  config: ParsedConfig,
): string | null {
  for (const div of config.activeDivisions) {
    if (div.head.agent && getAgentTier(div.head.agent) === tier) {
      return div.head.agent;
    }
  }
  return null;
}

/**
 * Find the head agent with the lowest tier number (highest authority).
 */
export function findHighestTierAgent(config: ParsedConfig): string | null {
  for (const searchTier of [1, 2, 3] as const) {
    const found = findAgentByTier(searchTier, config);
    if (found !== null) return found;
  }
  return null;
}


export function applyRouting(config: ParsedConfig, workDir: string): StepResult {
  const start = Date.now();

  try {
    const table = generateRoutingTable(config);
    const outPath = join(workDir, ".system", "routing-table.yaml");

    const yaml =
      "# AUTO-GENERATED by sidjua apply — DO NOT EDIT MANUALLY\n" +
      stringify(table, { indent: 2 });

    writeFileSync(outPath, yaml, "utf-8");

    logger.info("ROUTING", `Generated routing-table.yaml: ${table.routes.length} routes, default → ${table.default_route.agent}`);

    return {
      step: "ROUTING",
      success: true,
      duration_ms: Date.now() - start,
      summary: `${table.routes.length} routes, default → ${table.default_route.agent}`,
      details: {
        routeCount: table.routes.length,
        defaultAgent: table.default_route.agent,
        outPath,
      },
    };
  } catch (err) {
    throw new ApplyError(
      "GENERATION_ERROR",
      "ROUTING",
      `Routing step failed: ${err instanceof Error ? err.message : String(err)}`,
      err,
    );
  }
}
