// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Götz Kohlberg. All rights reserved.
// Dual licensed: AGPL-3.0 + SIDJUA Commercial License. See LICENSE.

/**
 * SIDJUA — Phase 6: Provider Layer types
 *
 * Unified LLM API abstraction. All future phases (7-12) depend on this interface.
 *
 * Key design decisions (from V1-RUNTIME-DECISIONS-Q5-Q12.md):
 *   - V1 providers: Anthropic + OpenAI. Interface supports future additions.
 *   - Streaming: NOT displayed. ALL data fully logged for audit.
 *   - Hot-Swap: Agent can switch provider mid-task. Messages are provider-agnostic.
 *   - Budget: Integrates with existing cost_ledger + cost_budgets DB tables (Phase 3).
 *   - Audit: Two new tables — provider_calls (summary) + provider_call_content (full body).
 *   - EventBus: Interface defined here; NoOpEventBus used in V1. Phase 7 provides real impl.
 *   - API keys: Retrieved from Secrets layer (Phase 3 Step 4). No plaintext anywhere.
 */


/** Supported LLM provider identifiers in V1. */
export type ProviderName = "anthropic" | "openai";

/** Model identifier string (e.g. "claude-sonnet-4-6", "gpt-4o"). */
export type ModelId = string;


/** Per-model token pricing in USD per 1 million tokens. */
export interface ModelPricing {
  /** Cost per 1M input (prompt) tokens in USD. */
  inputPerMillion: number;
  /** Cost per 1M output (completion) tokens in USD. */
  outputPerMillion: number;
}


/**
 * Configuration for a single provider instance.
 * API keys are NOT stored here — they are retrieved from the Secrets layer.
 */
export interface ProviderConfig {
  name: ProviderName;
  /** Secrets namespace from which to retrieve the API key. */
  secretsNamespace: string;
  /** Secrets key name within the namespace. */
  secretsKey: string;
  /** Default model to use when none is specified on a call. */
  defaultModel: ModelId;
  /** Optional request timeout in milliseconds (default: 60_000). */
  timeoutMs?: number;
}


/** Role of a message participant. "system" messages are provider-translated. */
export type MessageRole = "user" | "assistant" | "system";

/**
 * Provider-agnostic message. The registry translates these to
 * the native format of the active provider before each call.
 */
export interface Message {
  role: MessageRole;
  content: string;
}


/**
 * Full request to the provider layer.
 * Generated by the ProviderRegistry (adds callId); callers use ProviderCallInput.
 */
export interface ProviderCallRequest {
  /** UUID generated per call by the registry. */
  callId: string;
  agentId: string;
  divisionCode: string;
  provider: ProviderName;
  model: ModelId;
  messages: Message[];
  /** Optional system prompt. Takes precedence over role:"system" messages. */
  systemPrompt?: string;
  /** Maximum tokens to generate (provider default if unset). */
  maxTokens?: number;
  /** Sampling temperature (provider default if unset). */
  temperature?: number;
  /** Task identifier for cost attribution. */
  taskId?: string;
  /** Caller-supplied metadata (passed through to audit log). */
  metadata?: Record<string, unknown>;
}

/** Input from the caller; registry adds callId and resolves defaults. */
export type ProviderCallInput = Omit<ProviderCallRequest, "callId">;

/** Token counts returned by the provider. */
export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
}

/** Response from the provider layer after a successful call. */
export interface ProviderCallResponse {
  /** Echoed from the request. */
  callId: string;
  provider: ProviderName;
  model: ModelId;
  /** Concatenated text content of the response. */
  content: string;
  usage: TokenUsage;
  /** Actual USD cost computed from token usage + model pricing. */
  costUsd: number;
  /** End-to-end latency in milliseconds (request issued → response received). */
  latencyMs: number;
  /** Provider-reported stop reason (e.g. "end_turn", "stop", "length"). */
  finishReason?: string;
}


/**
 * Abstract provider interface. All V1 adapters (Anthropic, OpenAI, Mock)
 * and future adapters implement this.
 */
export interface LLMProvider {
  readonly name: ProviderName;

  /**
   * Execute a call to the LLM.
   * Streaming is not exposed — the full response is buffered and returned.
   * ALL call data is logged for audit regardless of success or failure.
   *
   * @throws ProviderError on API errors.
   */
  call(request: ProviderCallRequest): Promise<ProviderCallResponse>;

  /**
   * Estimate token count for a set of messages + optional system prompt.
   * Used for pre-call budget estimation. Actual token counts come from the response.
   */
  estimateTokens(messages: Message[], systemPrompt?: string): number;

  /**
   * Return true if the provider is reachable.
   * V1: checks that an API key is available. Does not make a network call.
   */
  isAvailable(): Promise<boolean>;
}


/** Exponential backoff retry configuration for provider calls. */
export interface RetryConfig {
  /** Maximum number of attempts (including the initial attempt). */
  maxAttempts: number;
  /** Delay before the first retry in milliseconds. */
  initialDelayMs: number;
  /** Maximum delay cap in milliseconds. */
  maxDelayMs: number;
  /** Multiplier applied to delay after each failed attempt. */
  backoffMultiplier: number;
}


/**
 * Result of a pre-call budget check.
 * If allowed is false, the call must not proceed.
 */
export interface BudgetCheckResult {
  /** Whether the call may proceed within budget. */
  allowed: boolean;
  divisionCode: string;
  currentDailyUsd: number;
  currentMonthlyUsd: number;
  dailyLimitUsd: number | null;
  monthlyLimitUsd: number | null;
  alertThresholdPercent: number;
  /** True if spend is within the alert threshold window (nearLimit → WARN event emitted). */
  nearLimit: boolean;
  /** Human-readable reason when allowed is false. */
  reason?: string;
}


/**
 * Minimal event bus interface. Phase 6 only emits events; it does not consume them.
 * Phase 7 provides the real pub/sub implementation. Phase 6 uses NoOpEventBus.
 */
export interface EventBus {
  emit(event: string, data: unknown): void;
  on(event: string, handler: (data: unknown) => void): void;
}

/** No-op event bus — all emits and subscriptions are silently discarded. */
export class NoOpEventBus implements EventBus {
  /** Emit is a no-op. Phase 7 provides a real EventBus. */
  emit(_event: string, _data: unknown): void {
    // intentional no-op
  }

  /** Subscribe is a no-op. Phase 7 provides a real EventBus. */
  on(_event: string, _handler: (data: unknown) => void): void {
    // intentional no-op
  }
}


/** Configuration for the ProviderRegistry. */
export interface RegistryConfig {
  /** Provider to use when none is specified on a call. */
  defaultProvider: ProviderName;
  /**
   * Fallback provider for failover.
   * If the primary provider fails after all retries, the registry
   * tries this provider once (without additional retries).
   */
  fallbackProvider?: ProviderName;
  retry: RetryConfig;
}


/**
 * Error thrown by a provider adapter.
 * isRetryable controls whether the retry handler will attempt another call.
 */
export class ProviderError extends Error {
  constructor(
    public readonly provider: ProviderName,
    /** Provider-specific error code (HTTP status, SDK error type, etc.). */
    public readonly code: string,
    message: string,
    /** True for transient errors (rate limits, 5xx). False for permanent errors (4xx, invalid key). */
    public readonly isRetryable: boolean,
    public override readonly cause?: unknown,
  ) {
    super(message);
    this.name = "ProviderError";
  }
}

/**
 * Thrown by the ProviderRegistry when a division's budget would be exceeded.
 * This blocks the call entirely — no provider is invoked.
 */
export class BudgetExceededError extends Error {
  constructor(
    public readonly divisionCode: string,
    public readonly period: "daily" | "monthly",
    public readonly limitUsd: number,
    public readonly currentUsd: number,
    public readonly estimatedCostUsd: number,
  ) {
    super(
      `Budget exceeded for division "${divisionCode}": ` +
        `${period} limit $${limitUsd.toFixed(4)}, ` +
        `current $${currentUsd.toFixed(4)}, ` +
        `estimated $${estimatedCostUsd.toFixed(4)}`,
    );
    this.name = "BudgetExceededError";
  }
}
