// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Götz Kohlberg. All rights reserved.
// Dual licensed: AGPL-3.0 + SIDJUA Commercial License. See LICENSE.

/**
 * SIDJUA — V1.1: Messaging Core Types
 *
 * Platform-agnostic types shared across messaging modules.
 * Adapters are identified by string channel names — no hardcoded enum.
 */


/**
 * Identifies the messaging platform. Defined by each adapter in AdapterMeta.channel.
 * Examples: "telegram", "discord", "email", "slack"
 */
export type MessagingChannel = string;


export interface Attachment {
  filename:   string;
  mime_type:  string;
  size_bytes: number;
  url?:       string;
}

/**
 * Normalised representation of an inbound message from any adapter.
 * Adapters translate their platform-specific payloads into this shape.
 */
export interface MessageEnvelope {
  /** Unique message ID (UUID generated by the adapter). */
  id:          string;
  /** Which adapter instance received this message. */
  instance_id: string;
  /** Adapter-defined channel identifier (matches AdapterMeta.channel). */
  channel:     MessagingChannel;
  sender: {
    platform_id:  string;
    display_name: string;
    /** True when the platform provides identity verification. */
    verified:     boolean;
  };
  content: {
    text:          string;
    attachments?:  Attachment[];
    /** ID of the message this is a reply to, if any. */
    reply_to?:     string;
  };
  metadata: {
    timestamp:    string;  // ISO 8601
    chat_id:      string;
    thread_id?:   string;
    platform_raw: unknown; // raw payload from the platform (for adapter use)
  };
}


export interface ResponseOptions {
  reply_to_message_id?: string;
  format?:              "text" | "markdown" | "html";
  attachments?:         Attachment[];
}


export interface UserMapping {
  sidjua_user_id:   string;
  instance_id:      string;        // bound to specific adapter instance
  platform_user_id: string;
  role:             "admin" | "user" | "viewer";
  created_at:       string;        // ISO 8601
  default_division?: string;       // optional division for task routing
}


/**
 * A single adapter instance as declared in governance/messaging.yaml.
 * One adapter plugin can power many instances with different configs.
 */
export interface AdapterInstanceConfig {
  /** Unique instance ID, e.g. "tg-team-alpha". */
  id:                 string;
  /** Adapter directory name, e.g. "telegram". */
  adapter:            string;
  enabled:            boolean;
  /** Adapter-specific config; validated against the adapter's JSON Schema. */
  config:             Record<string, unknown>;
  rate_limit_per_min: number;
}


export interface MessagingGovernance {
  /** If true, only mapped users can send messages. */
  require_mapping:              boolean;
  /** If true, users can register themselves via the platform. */
  allow_self_register:          boolean;
  /** Maximum response length in characters before truncation. */
  response_max_length:          number;
  /** Prepend short task ID to every agent response. */
  include_task_id_in_response:  boolean;
  /** Show "typing…" indicator while agent processes (adapter must support it). */
  typing_indicator:             boolean;
  /** Global inbound message rate cap across all adapter instances. */
  max_inbound_per_hour:         number;
}


export type MessagingAuditEvent =
  | "MESSAGE_RECEIVED"
  | "MESSAGE_AUTHORIZED"
  | "MESSAGE_REJECTED_UNAUTHORIZED"
  | "MESSAGE_REJECTED_RATE_LIMIT"
  | "MESSAGE_REJECTED_GOVERNANCE"
  | "RESPONSE_SENT"
  | "RESPONSE_FAILED"
  | "ADAPTER_LOADED"
  | "ADAPTER_UNLOADED"
  | "INSTANCE_STARTED"
  | "INSTANCE_STOPPED"
  | "INSTANCE_ERROR"
  | "USER_MAPPED"
  | "USER_UNMAPPED";


/** Governance override metadata — matches Task["governance_override"]. */
export interface GovernanceOverride {
  user_id:               string;
  override_at:           string;  // ISO 8601
  original_block_reason: string;
  original_block_rule:   string;
}

/** User-facing task input built from a MessageEnvelope. */
export interface UserTaskInput {
  description:        string;
  priority:           number;
  division:           string;
  budget_usd?:        number;
  ttl_seconds?:       number;
  source_metadata: {
    source_channel:     string;
    source_instance_id: string;
    source_message_id:  string;
    source_chat_id:     string;
    source_user:        string;
    attachments?:       Attachment[];
  };
  governance_override?: GovernanceOverride;
}

/** Minimal task handle returned when a message task is accepted. */
export interface MessagingTaskHandle {
  id:          string;
  description: string;
  agent_id:    string | null;
  budget_usd:  number | null;
  status:      string;
}

/** Governance blocked the task. */
export interface BlockResult {
  blocked:      true;
  reason:       string;
  rule:         string;
  overrideable: boolean;
}

/** Task was accepted and created. */
export interface AcceptResult {
  blocked: false;
  handle:  MessagingTaskHandle;
}

/** Union returned by submitMessageTask / submitTaskWithOverride. */
export type SubmitResult = BlockResult | AcceptResult;

/** Config for the message-to-task bridge. */
export interface TaskBridgeConfig {
  mode: "direct_passthrough";
  defaults: {
    priority:   number;
    budget_usd: number;
    ttl_seconds: number;
  };
  override: {
    enabled:                    boolean;
    window_seconds:             number;
    non_overrideable_rules:     string[];
    require_admin_for_override: string[];
  };
  /** channel → chat_id → division */
  channel_routing: Record<string, Record<string, string>>;
}

/** In-memory record of a blocked task awaiting user override decision. */
export interface PendingOverride {
  original_task:     UserTaskInput;
  original_envelope: MessageEnvelope;
  block_reason:      string;
  block_rule:        string;
  overrideable:      boolean;
  user:              UserMapping;
  created_at:        string;  // ISO 8601
  expires_at:        string;  // ISO 8601
}

/** Minimal audit log interface (duck-typed for testability). */
export interface AuditLog {
  log(event: string, data: Record<string, unknown>): void;
}
